# Generated by Django 4.0.3 on 2025-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('story', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('status', models.CharField(choices=[('AV', 'Disponibil'), ('PD', 'În proces'), ('AD', 'Adoptat')], default='AV', max_length=2)),
            ],
        ),
    ]
