# Generated by Django 4.0.3 on 2025-12-11 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_animals', to=settings.AUTH_USER_MODEL),
        ),
    ]
