# Generated by Django 4.0.3 on 2026-01-14 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_animal_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected'), ('FN', 'Finalized'), ('CN', 'Cancelled')], default='PD', max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('reason', models.TextField(help_text='De ce vrei să adopți acest animal?')),
                ('experience', models.TextField(help_text='Ai experiență cu animale?')),
                ('living_situation', models.CharField(help_text='Casă/Apartament, Curte, etc.', max_length=200)),
                ('visit_scheduled', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('visit_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='myapp.animal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adoptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
