# Generated by Django 4.0.3 on 2026-01-14 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('CF', 'Confirmed'), ('CM', 'Completed'), ('CN', 'Cancelled')], default='SC', max_length=2)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, help_text='Raport despre cum a decurs vizita')),
                ('animal_behavior', models.TextField(blank=True, help_text='Comportamentul animalului')),
                ('client_interaction', models.TextField(blank=True, help_text='Interacțiunea cu clientul')),
                ('recommendation', models.CharField(blank=True, choices=[('AP', 'Approve - Recomand adopția'), ('RJ', 'Reject - NU recomand adopția'), ('PD', 'Pending - Necesită vizită suplimentară')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='myapp.adoption')),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
