# Generated by Django 4.0.3 on 2026-01-14 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('AP', 'Approve'), ('RJ', 'Reject'), ('PD', 'Pending')], max_length=2),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WLK', 'Walk'), ('FED', 'Feed'), ('CLN', 'Cleaning'), ('BTH', 'Bath'), ('MED', 'Medication'), ('PLY', 'Play time'), ('TRN', 'Training'), ('OTH', 'Other')], max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('deadline', models.DateTimeField(help_text='Până când trebuie completată')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration in minutes')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AS', 'Assigned'), ('IP', 'In Progress'), ('CM', 'Completed'), ('CN', 'Cancelled'), ('OV', 'Overdue')], default='PD', max_length=2)),
                ('priority', models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HG', 'High'), ('UR', 'Urgent')], default='MD', max_length=2)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_round', models.IntegerField(default=0, help_text='Notifications round (0=none, 1-3=rounds)')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('DAILY', 'Zilnic'), ('WEEKLY', 'Săptămânal'), ('MONTHLY', 'Lunar')], max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='myapp.animal')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('notified_volunteers', models.ManyToManyField(blank=True, help_text='Volunteers who have been notified for this activity', related_name='notified_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['deadline', '-priority'],
            },
        ),
    ]
